local addonName, addon = ...

addon.variables.NewVersionTableEQOL = {
	["EQOL_UI"] = true,
	["EQOL_GENERAL"] = true,
	["EQOL_GAMEPLAY"] = true,
	["EQOL_SOCIAL"] = true,
	["EQOL_Questing"] = true,
	["EQOL_MapNavigation"] = true,
	["EQOL_SocialGeneral"] = true,
	["EQOL_DeathResurrect"] = true,
	["EQOL_VisibilityFrames"] = true,
	-- ["EQOL_GearUpgrades"] = true,
	["EQOL_Mailbox"] = true,
	["EQOL_PopupsAndUITweaks"] = true,
	["EQOL_autoAcceptSummon"] = true,
	["EQOL_autoAcceptResurrection"] = true,
	["EQOL_autoReleasePvP"] = true,
	["EQOL_quickSkipCinematic"] = true,
	["EQOL_questTrackerMinimizeButtonOnly"] = true,
	["EQOL_minimapButtonsMouseover"] = true,
	["EQOL_unclampMinimapCluster"] = true,
	["EQOL_mailboxRememberLastRecipient"] = true,
	["EQOL_frameVisibilityFadeStrength"] = true,
	["EQOL_uiScalePreset"] = true,
}
